version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - order-service
    environment:
      DEBUG_LOGGING_ENABLED: "true"

  user-service:
    build: ./services/user-service
    ports:
      - "4001:4001"

  order-service:
    build: ./services/order-service
    ports:
      - "4002:4002"
