name: Release Drafter (disabled)

# 🚫 Disabled for now. 
# To re-enable automatic release drafting, uncomment the `on:` section below.
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
